name: Pamela Ocampo
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
gems: ["emoji_for_jekyll"]
permalink: /words/:year/:month/:day/:title.html
