name: Pamela Ocampo
markdown: redcarpet
highlighter: pygments # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /words/:year/:month/:day/:title.html
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
jekyll-mentions: https://twitter.com
