blogTitle = "likes coffee"
blogUrl = "https://likescoffee.com/"
authorName = "Pamela Ocampo"
authorTwitter = "@pmocampo"
linkPrefix = "/"
googleAnalyticsId = "UA-47277958-1"
fbAdminsId = "1397070010"
